name: Update My M3U Playlist

on:
  schedule:
    # รันอัตโนมัติทุกวัน เวลา 00:00 น. (เวลา UTC) หรือ 07:00 น. เวลาไทย
    - cron: '0 0 * * *'
  workflow_dispatch: # ปุ่มกดรันเองแบบ Manual

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write # อนุญาตให้เขียนไฟล์ลง Repo ได้

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # เพิ่มบรรทัดนี้และ 1 บรรทัดบนเพื่อส่ง Token สิทธิ์

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python filter_m3u.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Update_playlist.m3u
        # ปรับมาใช้ echo แทน exit 0 เพื่อป้องกันกรณีไม่มีไฟล์ให้อัปเดตแล้วบอทแจ้งเออร์เรอร์
        git commit -m "Update playlist channels" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }} # ระบุปลายทางให้ชัดเจน
